import express from "express";
import {
  registerSalesHistoryForMonth,
  generateGeminiSalesReport,
  getSalesHistoryByYearController,
  createSaleAndInvoice,
  deleteSaleReport,
  askAboutReport,
} from "../controllers/sales";  

import { isAuthenticated } from "../middlewares";  

export default (router: express.Router) => {
  // Route to create a sale and invoice
  // This route handles POST requests to create a sale and generate the corresponding invoice. 
  router.post("/sales", isAuthenticated, createSaleAndInvoice);

  // Route to generate a sales report by month and year
  // This route handles POST requests to register sales history for a specific month. 
  router.post("/sales/report", isAuthenticated, registerSalesHistoryForMonth);

  // Route to generate a Gemini AI-specific sales report by ID
  // This route allows generating a personalized sales report for Gemini using the ID provided in the URL. 
  router.post("/sales/report-ai", isAuthenticated, generateGeminiSalesReport);

  // Route to ask about a sales report
  // This route allows the user to ask questions about a sales report generated by Gemini AI. 
  router.post("/sales/ask-about-ai/:id", isAuthenticated, askAboutReport);

  // Route to delete a sales report
  // This route handles DELETE requests to remove a sales report by its ID. 
  router.delete("/sales/report/:id", isAuthenticated, deleteSaleReport);

  // Route to get the sales history of a specific year
  // This route allows the user to retrieve sales history for a particular year. 
  router.get(
    "/sales-history/:year",
    isAuthenticated,
    getSalesHistoryByYearController
  );
};
